name: Continuous Integration

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Echo CMake Version
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --version

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/rkern/ -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: CC=clang CXX=clang++ cmake --build ${{runner.workspace}}/rkern --config $BUILD_TYPE
